"""Builds the app-icon tile from the bare mark.

The two files share one source of truth: `media-shuttle-bus.svg` is the mark, and the tile
places it on a container. They cannot be linked at runtime — an SVG loaded as an image is
not allowed to fetch another file — so the mark is inlined here instead of referenced.

    python docs/logo/build.py
"""

import pathlib
import re

HERE = pathlib.Path(__file__).parent
MARK = HERE / "media-shuttle-bus.svg"

# Each mark gets its own tile. Which one a given size should use is documented in
# README.md and demonstrated in preview.html.
VARIANTS = {
    "media-shuttle-bus.svg": "media-shuttle-icon.svg",
    "media-shuttle-bus-small.svg": "media-shuttle-icon-small.svg",
    "media-shuttle-bus-micro.svg": "media-shuttle-icon-micro.svg",
}

# Where each mark sits inside the tile, as (x, y, size) on the mark's own 1024 canvas.
# The smaller marks are placed larger: at 16px the tile's rounded corners already
# separate the icon from whatever is behind it, so margin is just wasted pixels, and
# the bus needs every one of the sixteen it can get.
PLACEMENT = {
    "media-shuttle-bus.svg": (44, 40, 936),
    "media-shuttle-bus-small.svg": (16, 28, 992),
    "media-shuttle-bus-micro.svg": (-50, -38, 1123),
}

# The mark is black and yellow, so the container has to hold a black silhouette without
# swallowing it. Red is the app's own accent and sits mid-luminance, which does that and
# keeps the icon on-brand; the rest are kept for comparison.
PRESETS = {
    "red":   ("#EC5C4D", "#D2372F", "#88201A", "#FFD9A0", 0.13),
    "slate": ("#5C6B85", "#33405A", "#1B2436", "#FFC74A", 0.16),
    "sky":   ("#DCE9F7", "#A9C3E0", "#7E9CC2", "#FFFFFF", 0.20),
    "dusk":  ("#8A6E9E", "#4A3C68", "#241E3A", "#FFB03A", 0.20),
    "night": ("#2A3346", "#161C29", "#090C13", "#FFC74A", 0.22),
}

TILE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024" role="img" aria-labelledby="iconTitle">
  <title id="iconTitle">Media Shuttle app icon</title>
  <!-- Generated by docs/logo/build.py from media-shuttle-bus.svg. Edit the mark, not this file. -->

  <defs>
    <!-- The container is lit from the same direction as the bus inside it. -->
    <linearGradient id="tile" x1="0.2" y1="0" x2="0.8" y2="1">
      <stop offset="0" stop-color="__T1__"/>
      <stop offset="0.45" stop-color="__T2__"/>
      <stop offset="1" stop-color="__T3__"/>
    </linearGradient>
    <!-- A warm pool behind the bus so the yellow has something to sit in. -->
    <radialGradient id="tileGlow" cx="0.5" cy="0.57" r="0.5">
      <stop offset="0" stop-color="__GLOW__" stop-opacity="__GA__"/>
      <stop offset="0.55" stop-color="__GLOW__" stop-opacity="0.07"/>
      <stop offset="1" stop-color="__GLOW__" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="tileSheen" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.16"/>
      <stop offset="0.5" stop-color="#FFFFFF" stop-opacity="0.03"/>
      <stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="tileFloor" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#000000" stop-opacity="0"/>
      <stop offset="1" stop-color="#000000" stop-opacity="0.38"/>
    </linearGradient>
    <clipPath id="tileClip"><rect x="0" y="0" width="1024" height="1024" rx="228"/></clipPath>
__MARK_DEFS__
  </defs>

  <g clip-path="url(#tileClip)">
    <rect width="1024" height="1024" fill="url(#tile)"/>
    <rect width="1024" height="1024" fill="url(#tileGlow)"/>
    <rect width="1024" height="420" fill="url(#tileSheen)"/>
    <rect y="700" width="1024" height="324" fill="url(#tileFloor)"/>
    <g transform="translate(__X__ __Y__) scale(__S__)">
__MARK_BODY__
    </g>
  </g>

  <!-- Container edge: a lit top lip, the way a physical tile catches light. -->
  <rect x="1.5" y="1.5" width="1021" height="1021" rx="226.5" fill="none"
        stroke="#FFFFFF" stroke-width="3" opacity="0.10"/>
  <path d="M228 3 H796 A225 225 0 0 1 1021 228" fill="none" stroke="#FFFFFF"
        stroke-width="3" opacity="0.15" stroke-linecap="round"/>
</svg>
"""


def tile(mark_name: str, preset: str) -> str:
    t1, t2, t3, glow, ga = PRESETS[preset]
    inset_x, inset_y, size = PLACEMENT[mark_name]
    mark = (HERE / mark_name).read_text(encoding="utf-8")

    defs = re.search(r"<defs>(.*?)</defs>", mark, re.S)
    body = mark[defs.end():] if defs else mark[mark.index("</title>") + 8:]
    body = body[: body.rindex("</svg>")]
    # The micro mark needs no gradients, so it has no <defs> of its own to inline.
    body = re.sub(r"<!--.*?-->", "", body, count=1, flags=re.S) if defs is None else body

    return (
        TILE.replace("__MARK_DEFS__", defs.group(1).rstrip() if defs else "")
        .replace("__MARK_BODY__", body.strip())
        .replace("__X__", str(inset_x))
        .replace("__Y__", str(inset_y))
        .replace("__S__", f"{size / 1024:.6f}")
        .replace("__T1__", t1)
        .replace("__T2__", t2)
        .replace("__T3__", t3)
        .replace("__GLOW__", glow)
        .replace("__GA__", str(ga))
    )


def main() -> None:
    import sys

    preset = sys.argv[1] if len(sys.argv) > 1 else "red"
    if preset not in PRESETS:
        raise SystemExit(f"Unknown preset {preset!r}; try one of {', '.join(PRESETS)}.")

    for mark_name, icon_name in VARIANTS.items():
        icon = tile(mark_name, preset)
        (HERE / icon_name).write_text(icon, encoding="utf-8")
        print(f"wrote {icon_name} [{preset}] ({len(icon):,} bytes)")


if __name__ == "__main__":
    main()
